[package]
name = "anneal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
libm = "0.2.1"
flo_draw = "0.3.0"
flo_canvas = "0.3.0"